manifest:
  version: 1.0
data:
  - en-US: Hello, World!
    id-ID: Halo, dunia!
  - en-US: I'm a software engineer and a Computer Science undergrad student.
    id-ID: Saya adalah seorang software engineer dan mahasiswa Teknik Informatika.